### ISSUE TITLE
Register New User

### ISSUE THREAD

**Issue by asherbig** [asherbig/MyFoodJournal#2]
As a new user, I want to be able to register.

Scenario: A new user of MyFoodJournal
Given the user opens the app
When they hit register and enter in their details,
Then the application should create the new account and load the default home page as if they had just logged in.

**Comment by charlesrmarcus** [comment]
Need to add logic to make usernames unique in DB and edit Password Error Flag. Update Username Regex for longer usernames.

**Comment by charlesrmarcus** [comment]
Make email a required field!
