### ISSUE TITLE
Build Wish List

### ISSUE THREAD

**Issue by asherbig** [asherbig/MyFoodJournal#3]
As a returning user, I want to be able to build a wish list of foods based on other reviews.

Scenario: A returning user of MyFoodJournal
Given the user clicks on a review for a food
When they want to add to their wish list, they will press a button,
Then the application should add the food (and review) to their wish list and navigate them to their wish list (or should it keep them on the same screen and give a notification that adding to their wish list was successful?)

**Comment by charlesrmarcus** [comment]
Originally planned for Sprint #2 but was moved due to issues with the DB update.
