### ISSUE TITLE
Edit Favorites List/Wish List

### ISSUE THREAD

**Issue by asherbig** [asherbig/MyFoodJournal#4]
As a returning user, I want to be able to edit a wish list of foods based on other reviews.

Scenario: A returning user of MyFoodJournal
Given the user is on their wish list tab
When the user presses the button to delete an entry from their wish list,
Then the application should remove the food from the wish list (and ask them if they want to rate the food?)

**Comment by charlesrmarcus** [comment]
Originally planned for Sprint #2 but moved due to issues with the DB update.
