### ISSUE TITLE
Favorite Dishes

### ISSUE THREAD

**Issue by zguthrie3** [asherbig/MyFoodJournal#6]
As a returning user of MyFoodJournal, I want to view dishes and meals that I have favorited in the past so I can easily view what foods at specific restaurants I have tried, and what I thought about said dishes.

Scenario: An experienced user of MyFoodJournal
Given this user has rated a food product before through the application
When the user logs into the application,
Then the user will automatically be taken to the My Reviews page, listing all of the reviews they have already taken.

**Comment by charlesrmarcus** [comment]
Moved to IceBox because of redundancy with Wish List story.
