### ISSUE TITLE
UI/UX - Reviews to Restaurants 

### ISSUE THREAD

**Issue by zguthrie3** [asherbig/MyFoodJournal#7]
As a returning user of MyFoodJournal, I want to quickly be able to access restaurant pages from other, previously reviewed food items.

Scenario: A returning user of MyFoodJournal
Given this user has rated a food product before through the application
When the user clicks on the name of the restaurant in the detailed review page,
Then the application navigates to the restaurant’s given page, and will load a menu preview that lets the user select another item off of the same menu.

**Comment by charlesrmarcus** [comment]
Search by User function!

**Comment by charlesrmarcus** [comment]
Moved to Sprint #4 for same DB update issues.
