### ISSUE TITLE
Search for Restaurants Function

### ISSUE THREAD

**Issue by zguthrie3** [asherbig/MyFoodJournal#8]
As a returning user of MyFoodJournal, I want to be able to search for restaurants in a given area by type of restaurant.

Scenario: A returning user of MyFoodJournal
Given this user is logged into an account on MyFoodJournal
When the user searches for new restaurant by a general term such as “mexican” or “pizza”,
Then the application should return all search results within a certain range that matches the criteria

**Comment by asherbig** [comment]
http://codetheory.in/google-place-api-autocomplete-service-in-android-application/
