### ISSUE TITLE
UI/UX - Moving Between Tabs

### ISSUE THREAD

**Issue by charlesrmarcus** [asherbig/MyFoodJournal#9]
** User Story **
As a new user of MyFoodJournal, I want to be able to move between the home page, reviews page, and other tabs so I can explore all that MyFoodJournal offers the user.

** Acceptance Criteria **
Scenario: A new user of MyFoodJournal
Given this user is already logged into MyFoodJournal,
When they press different tabs or menu buttons,
Then they will be able to find restaurants, reviews, and home tabs (etc.)

**Comment by zguthrie3** [comment]
Navigation drawer created on the feature branch.
